# https://fly.io/docs/reference/configuration/
app = 'ynews'
primary_region = 'ams'

[build]
dockerfile = 'Dockerfile'

[env]
DB_PATH = '/data/ynews.db'

[[mounts]]
source = 'sqlite_data'
destination = '/data'

[[vm]]
size = 'shared-cpu-1x'
memory = '256mb'
cpus = 1
